name: Windows
on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Build
        run: |
          go build ./src/*.go
          mv main.exe godecrypt.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GoDecrypt-Windows
          path: godecrypt.exe
